name: Maven Package and Attach to Release

on:
  release:
    types: [published]

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get JAR name
      id: get-jar
      run: echo "JAR_NAME=$(basename $(find ./target -name '*.jar'))" >> $GITHUB_ENV

    - name: Attach JAR to Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './target/${{ env.JAR_NAME }}'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
